# Generated by Django 4.2 on 2026-08-14 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "problem",
                    models.TextField(blank=True, verbose_name="Problème résolu"),
                ),
                ("solution", models.TextField(blank=True, verbose_name="Solution")),
                (
                    "target_audience",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Public cible"
                    ),
                ),
                (
                    "objectives",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Objectifs"
                    ),
                ),
                (
                    "business_model",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Modèle économique"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Catégorie"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idea", "Idée"),
                            ("preparation", "Préparation"),
                            ("development", "Développement"),
                            ("launched", "Lancé"),
                            ("growth", "Croissance"),
                        ],
                        default="idea",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Progression (%)"
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="Résumé")),
                (
                    "strengths",
                    models.JSONField(blank=True, default=list, verbose_name="Forces"),
                ),
                (
                    "weaknesses",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Faiblesses"
                    ),
                ),
                (
                    "opportunities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Opportunités"
                    ),
                ),
                (
                    "risks",
                    models.JSONField(blank=True, default=list, verbose_name="Risques"),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Recommandations"
                    ),
                ),
                (
                    "next_steps",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Prochaines actions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["owner", "status"], name="projects_pr_owner_i_4798b7_idx"
            ),
        ),
    ]
