# Generated by Django 4.2 on 2026-08-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("action_plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actionstep",
            name="phase",
            field=models.CharField(
                choices=[
                    ("phase-1", "Validation du concept"),
                    ("phase-2", "Architecture technique"),
                    ("phase-3", "Développement & test"),
                    ("phase-4", "Lancement"),
                ],
                default="phase-1",
                max_length=10,
                verbose_name="Phase",
            ),
        ),
    ]
