# Generated by Django 4.2 on 2026-08-14 17:38

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Adresse e-mail"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("entrepreneur", "Entrepreneur"),
                            ("freelance", "Freelance"),
                            ("student", "Étudiant"),
                            ("professional", "Professionnel"),
                            ("admin", "Administrateur"),
                        ],
                        default="entrepreneur",
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, verbose_name="Pays"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Bio")),
                ("website", models.URLField(blank=True)),
                ("linkedin", models.CharField(blank=True, max_length=200)),
                (
                    "profile_type",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Type de profil"
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Domaine"
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Compétences"
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                        verbose_name="Expérience",
                    ),
                ),
                (
                    "goals",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Objectifs"
                    ),
                ),
                (
                    "interests",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Centres d'intérêt"
                    ),
                ),
                (
                    "ai_preferences",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Préférences IA"
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False, verbose_name="Onboarding terminé"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
