# Generated by Django 4.2 on 2026-08-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.TextField(
                blank=True, verbose_name="Photo de profil (data-URL)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="E-mail vérifié"),
        ),
    ]
