# Generated by Django 4.2 on 2026-08-14 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Organisation"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("emploi", "Emploi"),
                            ("freelance", "Freelance"),
                            ("hackathon", "Hackathon"),
                            ("concours", "Concours"),
                            ("formation", "Formation"),
                            ("financement", "Financement"),
                            ("incubateur", "Incubateur"),
                            ("partenariat", "Partenariat"),
                            ("recherche", "Recherche"),
                        ],
                        default="emploi",
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Localisation"
                    ),
                ),
                (
                    "remote",
                    models.BooleanField(default=False, verbose_name="Télétravail"),
                ),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Date limite"),
                ),
                ("link", models.URLField(blank=True, verbose_name="Lien")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("closed", "Clôturée")],
                        default="active",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="opportunities.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watchlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["category", "status"], name="opportuniti_categor_eb29b5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="watchlist",
            unique_together={("user", "opportunity")},
        ),
    ]
