# Generated by Django 4.2 on 2026-08-17 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("opportunities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_opportunities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
